### ISSUE TITLE
Lỗi tạo dự án mới

### ISSUE THREAD

**Issue by vanduocvn87** [vmluan/sanyo#1]
Khi tạo dự án với thông số sau thì bị lỗi:
Project No: NITTO-SMZ-11JAN2012
Project Name: NITTO DENKO VIETNAM PHASE 4 PROJECT
Client: M/S SHIMIZU CORPORATION

Sau đó submit thì bị lỗi.

**Comment by vanduocvn87** [comment]
![project3](https://cloud.githubusercontent.com/assets/3634595/10812683/594a0fd8-7e4b-11e5-9d6a-9fb5c5e4c96c.png)

**Comment by hiepkhachbk** [comment]
Độ dài không đủ cho project_code và project_name.
Update code mới nhất. drop database và deploy lại

On Thu, Oct 29, 2015 at 2:43 PM, vanduocvn87 <notifications@github.com>
wrote:

> [image: project3]
> <https://cloud.githubusercontent.com/assets/3634595/10812683/594a0fd8-7e4b-11e5-9d6a-9fb5c5e4c96c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vmluan/sanyo/issues/1#issuecomment-152104273>.
>



-- 
THAI Chuong
YM/Skype : thaichuong159
Phone: (+84) 918776134
