### ISSUE TITLE
Lỗi ko back lại trang trước đó được (Anh Trọng)

### ISSUE THREAD

**Issue by vanduocvn87** [vmluan/sanyo#3]
![linkbacknotfound](https://cloud.githubusercontent.com/assets/3634595/10840066/c0a39f88-7f0d-11e5-867e-03c44035c5a5.png)

**Comment by hiepkhachbk** [comment]
Đã fix trong comment của Luân #1

**Comment by hiepkhachbk** [comment]
Fixed trong #1
